### ISSUE TITLE
Projections behaving awkwardly on Tiling Window Managers

### ISSUE THREAD

**Issue by NK-Nikunj** [UIUC-PPL/projections#104]
**Environment (please complete the following information):**
 - OS: Arch Linux (kernel 5.7.10) running bspwm (a tiling window manager)
 - Projections Version: 10.0
 - Java Version: 14.0.2
 - Charm++ Version: commit 05a360eb0

**Describe the bug**

As the title suggests, the experience of running projections are not ideal. Following are the issues:
 * Projections does not respect Xresources's dpi settings. So the text/images are really small on a 4k laptop screen.
 * Projections does not respect tile boundaries. It assumes that whole screen is allotted to it. So when I add another tile (say terminal), it does not adjust to half screen but cuts itself into half. See [here](https://imgur.com/a/Jo0fk2c) for visual reference.
 * Projections does not register single mouse clicks. So if I click on the toolbar for dropdown, I see that it registers a double click (or something similar) that causes it to open the dropdown and immediately close it.
 * Some tools don't work as expected. For example, under timeline view. It does seem to generate the timeline but it is never shown to the user. See [here](https://imgur.com/a/wh4caEp) for a visual reference.

**To Reproduce**
Run projections on any tiling window manager (i3wm, bspwm, awesome wm, dwm etc.)

**Expected behavior**
Projections should run properly.

**Comment by rbuch** [comment]
Hmm, I'm not able to reproduce this under i3. See the attached image, which shows that tile boundaries are respected and timeline is shown. Single clicking also works fine for me. Is there perhaps something else that could be causing this? Doing a bit of searching online makes it seems like Java (likely Swing, specifically) doesn't play terribly nicely with bspwm. Are you able to use other Java programs without issues?

![image](https://user-images.githubusercontent.com/304273/88731015-977b5600-d0fc-11ea-9554-d0c8b0a76aba.png)

**Comment by NK-Nikunj** [comment]
I don't do any java programming really. I had to install java to run projections so I can't tell if its a java issue. Do you have any set of tests that I can run to check if its a java issue?

**Comment by rbuch** [comment]
I don't really have any tests to check; I think the best thing to do is just run some other Java programs with GUIs. Perhaps you can try running [VisualVM](https://visualvm.github.io/) or some other Java program you find to see how that gets rendered.

**Comment by NK-Nikunj** [comment]
@rbuch apologies for the delay. Yes, it does seem like a java issue instead of projections issue. I'm experiencing similar issues with VisualVM (version 2.0.3).

Closing as the cause is orthogonal to projections.
