### ISSUE TITLE
Display warning if user tries processing large logs

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/projections#12]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/440*

---
If the user selects a large number of processes or large time intervals on large logs, display some warning to ensure users don't unknowingly overstress their machines.

**Comment by pplimport** [comment]
*Original author: Nikhil Jain*
*Original date: 2014-05-26 05:24:11*

---
Assigned to Zhengqi since he submitted a patch for it.

**Comment by pplimport** [comment]
*Original author: Zhengqi Yang*
*Original date: 2014-05-29 19:05:40*

---
Merged on gerrit.
