### ISSUE TITLE
usage profile and extrema does not display correctly for Apoa1 NAMD

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/projections#13]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/455*

---
The logs are here
/fastscratch/Yanhua/logs_apoa1

Select 8 timesteps and display in usage profile, check for example PE 7, the utilization is wrong 
Extreme of least idle is totally messed up.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-05-05 16:58:10*

---
Since there is no progress from Ronak, I will delegate this to Maxx.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-09-04 16:25:23*

---
Implemented and checked in

**Comment by rbuch** [comment]
*Original date: 2014-09-04 20:08:34*

---
Has this been merged?  The gerrit page (http://charm.cs.uiuc.edu/gerrit/#/c/282/) does not show that it has been.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-09-04 20:24:47*

---
In the git log, I saw a commit for this bug

**Comment by rbuch** [comment]
*Original date: 2014-09-04 21:12:36*

---
Commit 4c8e9b6b726a332df21a433a626d5be85e6b5e36 only fixes the usage profile error, not the extrema error.
