### ISSUE TITLE
inline and local entry method can not be tracked back 

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/projections#15]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/459*

---
In projections, if you click on a entry method which is inline or local, it can not be traced back.  This is due to the nested begin_processing entries
in the log. 

We want to trace it to its parent entry method.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-04-09 18:01:52*

---
Any progress?

**Comment by rbuch** [comment]
*Original date: 2014-04-09 18:20:59*

---
Not yet, I've been busy with class.  I'll have time later today or tomorrow.

**Comment by ericjbohm** [comment]
*Original date: 2014-04-24 17:44:36*

---
Any progress on this?  It has been 2 weeks.

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-05-22 16:28:45*

---
Any progress on this?

**Comment by ericjbohm** [comment]
*Original date: 2016-09-28 18:45:32*

---
Status?

**Comment by stwhite91** [comment]
*Original date: 2018-02-16 05:57:50*

---
Does the related bug #937 fix this entirely?

**Comment by pplimport** [comment]
*Original author: Seonmyeong Bak*
*Original date: 2018-02-16 20:27:07*

---
It does but the issue is https://charm.cs.illinois.edu/redmine/issues/937 doesn't work in case when inline entry method calls local entry methods inside. 
I'm figuring out how to solve this.

**Comment by rbuch** [comment]
*Original date: 2018-08-08 16:26:09*

---
Fixed in ~~https://charm.cs.illinois.edu/gerrit/#/c/charm/+/3723/~~ https://github.com/UIUC-PPL/charm/commit/8a7c99369b1f37dccd9dbd2328370db5d4ae24e0
