### ISSUE TITLE
Add new image output formats

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/projections#22]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/515*

---
I received an in-person request for vector graphics output (svg preferred, but we might as well support things like pdf and eps) from Projections for ease of including them in papers and allowing things like lossless zoom.  Additionally, the ability to use a white background should be made more clear, as that is more amenable to inclusion in papers.

**Comment by rbuch** [comment]
*Original date: 2014-06-10 12:00:53*

---
This should be doable fairly easily with Batik (http://xmlgraphics.apache.org/batik/).

**Comment by PhilMiller** [comment]
*Original date: 2015-02-11 06:20:21*

---
Passing open Projections Features with non-existent or departed assignees to Ronak for triage and re-assignment.
