### ISSUE TITLE
"Change Colors" from Usage Profile Does Nothing

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/projections#23]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/517*

---
From the Usage Profile view, Tools -> Change Colors does not do anything.  It should open a new window that allows the user to select new colors (cf. operation from the Time Profile graph view)

**Comment by pplimport** [comment]
*Original author: Maxx Macica*
*Original date: 2014-06-13 13:58:43*

---
I actually already implemented this and will commit it once I know my other usage profile bugs have been fixed.

**Comment by pplimport** [comment]
*Original author: Maxx Macica*
*Original date: 2014-08-26 17:55:41*

---
Merged on Gerrit.
