### ISSUE TITLE
Command Line Arguments with Spaces Incorrectly Parsed

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/projections#24]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/518*

---
When attempting to load a file on the command line with a path that contains a space, the parser splits on the space.

For example:
ronak`machine:~$ projections ~/Test\ Dir/test.sts 
Internal Error: Path [/home/ronak/Dir] supplied for file detection is not a directory! Please report to developers!

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-09-04 16:23:01*

---
This is also fixed, right? If so, please close it.
