### ISSUE TITLE
Usage Profile is blank and shows incorrect selection range for application run with +sumDetail

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/projections#46]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1283*

---
I compiled leanmd with +tracemode summary and ran it with +sumDetail. On opening the leanmd.sum.sts file with projections visualization tool and selecting usage profile, End Time in the range selection is shown as 2441000.0000000001 s, which is invalid. 
On selecting that invalid range (or a valid range like 0 - 2.4 ms), a blank usage profile is shown. 

![Snip20161106_3](https://user-images.githubusercontent.com/1772435/63629983-dd21cb80-c5db-11e9-98e4-7b4a2a26b45d.png)
![Snip20161106_4](https://user-images.githubusercontent.com/1772435/63629984-dd21cb80-c5db-11e9-8d2c-5cd94b43f1ea.png)

**Comment by nitbhat** [comment]
*Original date: 2016-11-06 17:19:57*

---
The leanmd.0.sum file seems to have been generated correctly. It is almost the same as the leanmd.0.sum generated without the +sumDetail option. In the case of +sumDetail not being supplied, the visualization tool behaves correctly by showing a valid range and populating the usage profile correctly.

**Comment by rbuch** [comment]
*Original date: 2016-11-07 22:52:57*

---
This happened because there was a .projrc file in Nitin's logs that had cached an erroneous time.  This was fixed in commit 3c53c27c7bac23cf0e31ad7f7fe049a9dc58865c.
