### ISSUE TITLE
Projections summary shows 0s for EP Exec Time for a single core large ChaNGa job 

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/projections#47]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1293*

---
EPExecTime has a large number of zeros. 

To reproduce this issue: 
1) Compile charm with enable-tracing. 
./build ChaNGa netlrts-linux-x86_64 smp --enable-tracing --with-production -j4

2) After downloading ChaNGa, change its makefile to add -tracemode summary to LDFLAGS.

3) Point ChaNGa to charm
export CHARM_DIR=/dcsdata/home/nbhat4/Work/software/changa/charm

4) Compile ChaNGa
make -j4

5) Place the input file ./snapshot1M.param in the same directory as ChaNGa. I've stored the input files (snapshot1M .param and .std) in /scratch/nitin/changa/inputFiles/ on charity). 

6) Run changa on one core (with or without +sumDetail)
./charmrun +p1 ++ppn 1 ./ChaNGa -n 1 -p 2 -b 32 +bench +traceroot ./proj_summ_logs_32/ +sumDetail ./snapshot1M.param +pemap 1 +commap 0 > changa_output

7) Open the traceroot directory and try opening the ChaNGa.0.sum file and look at the EPExecTime row. (A lot of entry methods have their values as zero).

**Comment by rbuch** [comment]
*Original date: 2017-02-14 18:32:09*

---
This is correct as far as I know, those EPs just didn't have attributable time.  This was part of a bigger issue where Projections was using cached values that made analysis appear incorrect that was fixed.
