### ISSUE TITLE
Nomal/Compact/SuperCompact views are now missing on Mac

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/projections#52]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1885*

---
Since the update to use Mac menu bars, the View options for "Normal", "Compact", and "Super compact" are now gone.
They are useful when examining traces on more PEs than can fit on the screen.

**Comment by matthiasdiener** [comment]
*Original date: 2018-04-25 15:59:41*

---
(Partial?) fix here: https://charm.cs.illinois.edu/gerrit/#/c/projections/+/4058/
