### ISSUE TITLE
timeline does not show correctly about idle overhead

### ISSUE THREAD

**Issue by pplimport** [UIUC-PPL/projections#8]
*Original author: Yanhua Sun*
*Original issue: https://charm.cs.illinois.edu/redmine/issues/435*

---
I do not know whether others have this problem.  I found that after we added SDAG_RTS entry 
in Charm, the time profile , usage profile in Projections can not display correctly. 

In timeline, the SDAG_RTS seems not much time. However, when using time profile, it is totally messed up. All overhead time goes away. Instead, it is all SDAG_RTS time. This is wrong.

The projections data can be found here 

/dcsdata/home/jessie/PPL/git/benchmarks/leanmd/prj_root

**Comment by pplimport** [comment]
*Original author: Yanhua Sun*
*Original date: 2014-03-31 18:26:50*

---
Ronak, any progress on this?

**Comment by rbuch** [comment]
*Original date: 2015-02-09 22:12:34*

---
While the logs at /dcsdata/home/jessie/PPL/git/benchmarks/leanmd/prj_root do indeed display erroneous behavior, it is suspicion that the logs themselves are at fault.  I went through and manually calculated the values directly, and they seem to be correct.  I was unable to reproduce the issue with new logs.  Unless somebody can provide logs from a "modern" build of Charm, this should be rejected.
