### ISSUE TITLE
Change Default Extrema Analysis View to "Least Idle Time"

### ISSUE THREAD

**Issue by rbuch** [UIUC-PPL/projections#9]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/436*

---
The majority of people who use extrema analysis use the "least idle time" view.  Change the GUI so that this is the default choice.

**Comment by pplimport** [comment]
*Original author: Zhengqi Yang*
*Original date: 2014-03-18 21:01:38*

---
Added this feature by simply change the default index of the attribute list to be 1(which is "Least Idle Time") in projections.Tools.Extrema.ExtremaDialogExtension.java.

This can also be implemented by exchanging the entries in "String attributes" in projections.Tools.ExtremaWindow.java.

Now I am wondering how to commit this change.

**Comment by pplimport** [comment]
*Original author: Zhengqi Yang*
*Original date: 2014-03-18 21:13:42*

---
By the way, I also tried to use doxygen to generate some documents. They looks messy but are really helpful.
